---
title: "Contribution Summary"
author: "A Cavalla"
date: "01/04/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Contribution Summary

A concise summary of contributions of each group member (4 pts)

Describes the tasks and contributions of each of your group members
Do you think the task assignments were fairly assigned and appropriate given each member's background and skills? If no, how would you change it?

Fangwu Wang:

Rawnak Hoque:

Somdeb Paul:

Anna Cavalla: Helped with identification of datasets; DNA methylation analysis, motif identification on promoter sequences & associated poster section; introduction section and curating/spell checking poster; general repo upkeep. -- It may have been more beneficial for me to be working on RNA-seq analysis since it is more relevant to my own research, but it was interesting to use a new suite of tools and perform some motif discovery anyhow.



Your specific contributions and comments (4 pts)

Explain what are your contributions to the project?
What worked well and what did not? What was the most challenging or rewarding moment during your group project?
How did you find having members of different backgrounds for a scientific project?
What have you learned from this group project?
Any other comments on how the group project could have been structured differently (i.e. delivery requirements, assessment“)

Fangwu Wang:

Rawnak Hoque:

Somdeb Paul:

Anna Cavalla: I had input into the identification of a suitable dataset, performed the promoter analysis on differentially methylated regions of the genome, co-wrote, curated and spellchecked the poster.
Identification of a suitable dataset I found to be one of the hardest parts of the project, since before that, the question seemed impossibly open-ended, with almost too much variety. Within available datasets however, as soon as we found one which seemed appropriate, it often turned out to be unsuitable in some way (since as a newbie it can sometimes be hard to discern which problems are unworkable and which can be worked around) and this became quite frustrating. 
I found the inclusion of members from different backgrounds (whom I did not previously know) to be rewarding and instructional, since the problem was approached from different ways of thinking.
Multidisciplinary working groups are valuable; datasets can be elusive; defining the problem diminishes the problem; any new experience in data analysis has its own teething problems but is valuable!