---
title: "RNASeq_analysis"
author: "Rawnak Hoque"
date: "March 15, 2017"
output: html_document
---


## Deferentially expressed genes in normal data
The normal data lack replicates, so we created a heatmap for quality check and detected an outlier. We removed one GMP sample from there.
The resulted heatmap is [here](https://github.com/STAT540-UBC/team_Bloodies/blob/master/Data/RNA-seq/Normal/results/reformed-heatmap.pdf)

The follwoing [Rscript](https://github.com/STAT540-UBC/team_Bloodies/blob/master/Data/RNA-seq/Normal/code/RNASeq_normal.R) was used to analyse the data. 

## Deferentially expressed genes in leukemia data
 

A list of deferentially expressed genes in two groups of leukemia samples were generated using limma and edgeR Bioconductor packages. 
The R scipt is [here](https://github.com/STAT540-UBC/team_Bloodies/blob/master/Data/RNA-seq/Leukemia/code/RNASeq_leukemia_limma.R) 

In each of the groups or subtype of leukemia we had 7 replicates with RNASeq raw count data.
We normalizes the data and fit into linear model 
We created a mean difference [plot](https://github.com/STAT540-UBC/team_Bloodies/blob/master/Data/RNA-seq/Leukemia/results/log-expression-fold-change.pdf) displaying the log-fold-changes and average A-values for each gene.
The P-value distribution were plotted [here](https://github.com/STAT540-UBC/team_Bloodies/blob/master/Data/RNA-seq/Leukemia/results/p-value-distribution.pdf). The values are not uniformly distributed which indicates the null hypothesis is rejected or there are significant differences between the two leukemia groups(AML and CLL).

The top 9000 deferentially expressed  [genes](https://raw.githubusercontent.com/STAT540-UBC/team_Bloodies/master/Data/RNA-seq/Leukemia/results/toptable.txt?token=AX06pOlK3uKeRoJeLjChSs2TmFcoubz7ks5Y0zE4wA%3D%3D) having P value <=0.05 were detected. 

The following [Rscript] (https://github.com/STAT540-UBC/team_Bloodies/blob/master/Data/RNA-seq/Leukemia/code/RNASeq_leukemia_limma.R) was used to analyze the data.

